In [30]:
import numpy as np

In [31]:
np.random.randn(4, 4)

array([[ 2.74658322,  0.82064283, -1.28157393,  0.15080327],
       [ 1.23299289,  1.26994961, -0.09353699, -1.00689199],
       [-0.13601664,  0.53414119,  1.77399181, -0.07667977],
       [ 0.03295266, -1.23899367,  0.10855079,  0.05722601]])

In [32]:
# 生产一个3行4列的2维零数组,类型为64位浮点型
zeros_float_arr = np.zeros((3,4), dtype=np.float64)

In [33]:
zeros_float_arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [34]:
arr = np.array([[1,2,3],
               [4,5,6]])

In [35]:
# 矢量与矢量的计算
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
print(arr+arr)
print(arr*arr)

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


In [37]:
# 标量与矢量的计算, 先将标量广播成为矢量
1 + arr


array([[2, 3, 4],
       [5, 6, 7]])

In [40]:
# 多维数组
arr_3_3 = np.arange(9).reshape(3,3)

In [41]:
arr_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
# 多维数组的切片
arr_3_3[1:,1:]

array([[4, 5],
       [7, 8]])

In [43]:
# 条件索引

con_arr = np.array([[True, False, False],
                    [False, True, False],
                    [False, False, True]])

filtered_arr = arr_3_3[con_arr]

In [44]:
filtered_arr

array([0, 4, 8])

In [47]:
# 转置 transpose
# 高维数组转置要指定维度编号(0, 1, 2 ...)
transpose_arr = arr_3_3.transpose()

In [48]:
transpose_arr

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [53]:
# 求和
arr = np.arange(10).reshape(5,2)
print(arr)

# 全部元素求和
print(np.sum(arr))
# 列元素求和
print(np.sum(arr, axis=0))
# 行元素求和
print(np.sum(arr, axis=1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
45
[20 25]
[ 1  5  9 13 17]


In [60]:
arr2 = np.arange(24).reshape(4,3,2)
print(arr2)

print("axis=0:\n",np.sum(arr2, axis=0))
print("axis=1:\n",np.sum(arr2, axis=1))
print("axis=2:\n",np.sum(arr2, axis=2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
axis=0:
 [[36 40]
 [44 48]
 [52 56]]
axis=1:
 [[ 6  9]
 [24 27]
 [42 45]
 [60 63]]
axis=2:
 [[ 1  5  9]
 [13 17 21]
 [25 29 33]
 [37 41 45]]
